CREATE TABLE [dbo].[hole_score]
(
	[id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [player_id] UNIQUEIDENTIFIER NOT NULL, 
    [round_id] UNIQUEIDENTIFIER NOT NULL,
    [hole_id] UNIQUEIDENTIFIER NOT NULL,
	[game_id] UNIQUEIDENTIFIER NOT NULL,
    [strokes] INT NOT NULL
)
